# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e271e1131494279a5340dfad6204759ef9508a53ce8aadbaae81f43532e84eb71661fe4c2b17e9838610a6397845398408c3d1ccc302bd07ed9759e14afaa66c

test:
  secret_key_base: c3130d5095cd058c5b37bc18600eca48c57bb49ad04a75e64f788c6e9179e5dd1d83e91c143343340676a6e91b5947a85c7a03f149b855c32e3be37831e4d67b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
